---
title: "[TIL] DAY8 계산기 Lv1 트러블 슈팅"
categories: [내일배움캠프, TIL]
tag: [개인 과제, 본캠프, 트러블슈팅, 예외처리, 자바, 입력처리]
date: 2025-02-26 21:00:00 +0900
toc_sticky: true
---
### TODO
***
✔️ 자바 기초 문법 다지기 2주차 정리

✔️ 자바 기초 문법 다지기 3주차 완강

✔️ 계산기 개인 과제 Lv1 완료

✔️ TIL 작성

### 오늘 배운 것
***
#### 연산자 입력 문제
연산자를 입력 받을 때는 크게 어려운 점은 없었으나 숫자를 입력 후 연산자를 입력할 때 입력이 정상적으로 처리되지 않는 문제가 있었다.

nextLine()을 한 번 추가하고 하는 방식도 있었지만, 코드가 길어져서 처음부터 next()로 받는 것을 선택했다.

```java
    private void inputOperator() {
        System.out.print("사칙연산 기호를 입력하세요 (+, -, *, / 가능): ");
        operator = sc.next().charAt(0);
        if (!operatorArr.contains(operator)) {
            System.out.println("잘못된 사칙연산 기호입니다. 다시 입력해주세요.");
            inputOperator();
        }
    }
```

다음은 next()와 nextLine()의 차이점을 알아보았다.
- `next()`
  - `공백(스페이스, 탭)`을 기준으로 첫 번째 단어만 읽음
  - 단일 단어 입력을 받을 때 적절
- `nextLine()`
  - `줄바꿈(엔터)`를 기준으로 전체 입력을 한 줄 단위로 읽음
  - 문장 단위 입력을 받을 때 적절

#### 연산 기능 예외 처리
연산 기능 구현 중, 0으로 나누는 경우 `ArithmeticException`이 발생하여 프로그램이 강제 종료되는 문제가 있었다. 

자바에서는 0으로 나누는 연산에서 예외가 발생하며, 별도의 예외 처리를 하지 않으면 프로그램이 종료된다. 

```java
    private int calculateResult() {
        try {
            switch (operator) {
                case '+':
                    result = num1 + num2;
                    break;
                case '-':
                    result = num1 - num2;
                    break;
                case '*':
                    result = num1 * num2;
                    break;
                case '/':
                    if (num2 == 0) {
                        throw new ArithmeticException("0으로 나눌 수 없습니다.");
                    }
                    result = num1 / num2;
                    break;
            }
        } catch (ArithmeticException e) {
            System.out.println(e.getMessage());
            result = -999;
        }
        return result;
    }
```

이를 해결하기 위해 try-catch문을 사용하여 해결했다. 입력 받은 두 번째 숫자가 0이고 연산자가 /인 경우 결과는 -999로 출력하게 했다. 다른 방법이 더 있는지는 Lv2를 진행하면서 알아봐야겠다.


#### 숫자 입력 무한 루프
숫자가 아닌 다른 문자를 입력한 경우 `InputMismathException`이 발생하도록 했고 재귀 호출하여 다시 입력을 받도록 했다.

그러나 예외 발생 시 남아있던 개행 문자가 입력 버퍼에 남아 있어 nextInt() 호출 시 재입력을 받지 못하고 무한루프가 발생했다.

```java
private void inputNumber() {
  try {
    System.out.print("양의 정수 두 개를 입력하세요 (0부터 입력 가능): ");
    num1 = sc.nextInt();
    num2 = sc.nextInt();
    if (num1 < 0 || num2 < 0) {
      System.out.println("양의 정수만 입력이 가능합니다. 다시 입력해주세요.");
      inputNumber();
    }
  } catch (InputMismatchException e) {
    System.out.println("다른 문자를 입력했습니다. 올바른 숫자를 입력해주세요.");
    sc.nextLine(); // 무한루프 방지
    inputNumber();
  }
}
```

이를 해결하기 위해 예외 발생 시 `nextLine()`을 호출하여 입력 버퍼를 비우고 다시 입력을 받을 수 있도록 수정했다.

### 느낀점
***
항상 이런 문제를 해결할 때마다 느끼는 건 기능을 구현하는 것 보다 예외를 발견하고 처리하는 것이 더 힘들다는 점이다. 정해진 요구사항 외의 부분은 결국 개발자의 몫이니까 말이다. 지금 -999로 처리해둔 부분이 매우 신경쓰인다. 내일 Lv2를 진행하면서 저 부분도 수정할 방법을 찾아봐야겠다.

### 내일 학습할 것
- 계산기 Lv2 시작하기
- 계산기 Lv1 연산 부분 예외처리 생각해보기
- 자바 3주차 강의 정리하기
- 백준 1문제 풀기
